# Introducción

En este informe se presentan los principales resultados del estudio panel Educación y Meritocracia, realizado durante el 2023 y 2024. El objetivo de este estudio es analizar cómo la escuela contribuye en los aprendizajes y actitudes sobre la meritocracia en la escuela y en el país, así como su relación con la educación cívica y la formación ciudadana. Se examinan las percepciones de los y las estudiantes sobre la justicia en sus calificaciones y cómo estas reflejan el mérito individual, así como el papel de la escuela en la promoción de valores y comportamientos cívicos.

La escuela se posiciona como un actor crucial en la reproducción de la meritocracia dentro de la socialización política de las/los estudiantes. Este fenómeno se manifiesta a través de la educación cívica impartida en los colegios, particularmente desde las ideas presentes en el currículo de Formación Ciudadana. En este contexto, los vínculos entre la idea del **mérito individual** y la **vida en común** resultan especialmente interesantes de estudiar, ya que representan una contradicción dentro de la formación de los futuros ciudadanos activos en la sociedad.

La *meritocracia en la escuela* se refleja principalmente en las creencias y prácticas desarrolladas en el aula. Esto se evidencia particularmente en la experiencia que los estudiantes tienen con sus notas, ya que las calificaciones funcionan como recompensas basadas en el mérito individual del estudiante. De esta manera, las/los estudiantes utilizan criterios de justicia para evaluar si sus notas recompensan de manera justa dicho mérito.

Contrariamente a la experiencia meritocrática en el aula, se presenta el rol socializador de la escuela a través de los criterios de ciudadanía enseñados en el ámbito de la *Formación Ciudadana*. En este aspecto, las escuelas promueven un desarrollo sociopolítico en los jóvenes, abarcando dimensiones actitudinales, cognitivas y comportamentales. Esto incluye aspectos civiles, prosociales, comunitarios, cívicos y formales, articulando un modelo ideal de comportamiento en sociedad entendido como buena ciudadanía. Este enfoque impacta en la socialización de prácticas cohesivas que los jóvenes aplicarían como ciudadanos activos en la sociedad chilena.

Con esto en mente, este informe pretende estudiar *en qué medida un sistema educativo caracterizado por una economía moral que enfatiza logros individuales es capaz de promover efectivamente los comportamientos y valores políticos y sociales asociados a los contenidos de formación ciudadana*.

El informe se divide en tres secciones siguientes. Primero, se presenta un reporte metodológico sobre las principales características del estudio realizado. Segundo, se incluyen los principales resultados sobre las percepciones y actitudes hacia la meritocracia que tienen estudiantes, apoderados y profesores. Se presenta una sección sobre los principales resultados asociados a las percepciones, creencias y actitudes sobre Ciudadanía y formación ciudadana. Finalmente, se expondrá una sección referida a un Experimento Distribucional de Encuesta (DSE) implementado en esta edición del estudio, que pretende evidanciar los criterios de justicia que emplean estudiantes a la hora de distribuir décimas en el contexto escolar.
