---
title: "Meritocracia 1"
---

```{r, data, echo=FALSE}
pacman::p_load(dplyr, sjPlot, stargazer, kableExtra, texreg, haven, sjlabelled,
               ggplot2, summarytools, ggtext, ggpubr, hrbrthemes, tidyr, stringr, 
               sjmisc, ggalluvial, shadowtext)

#Data

load("input/data/original/edumer_students_long.RData")

load("input/data/original/db_proc_students_w02.RData")
```

```{r, preparacion, echo=FALSE, message=FALSE}
# Codificamos los valores 99-88 como missing para todas las variables
db_long <- edumer_students_long %>% set_na(., na = c(99, 88))

# Iteramos la recodificación de etiquetas para cada variable y fraseo

for (i in names(dplyr::select(db_long, tidyselect::starts_with("p1_"), starts_with("p2_"), starts_with("p8_"), starts_with("p9_"), starts_with("p17_")))) {
  db_long[[i]] <- sjlabelled::set_labels(
    x = db_long[[i]],
    labels = c("Muy en desacuerdo", "En desacuerdo", "De acuerdo", "Muy de acuerdo")
  )
}


for (i in names(dplyr::select(db_long, tidyselect::starts_with("p10_")))) {
  db_long[[i]] <- sjlabelled::set_labels(
    x = db_long[[i]],
    labels = c("Nada importante", "Algo importante", "Importante", "Muy importante")
  )
}


for (i in names(dplyr::select(db_long, tidyselect::starts_with("p11_")))) {
  db_long[[i]] <- sjlabelled::set_labels(
    x = db_long[[i]],
    labels = c("Seguro no haré esto", "Tal vez haré esto", "Probablemente haré esto", "Seguro haré esto")
  )
}

for (i in names(dplyr::select(db_long, tidyselect::starts_with("p12_")))) {
  db_long[[i]] <- sjlabelled::set_labels(
    x = db_long[[i]],
    labels = c("Si", "No")
  )
}

for (i in names(dplyr::select(db_long, tidyselect::starts_with("p13_")))) {
  db_long[[i]] <- sjlabelled::set_labels(
    x = db_long[[i]],
    labels = c("Nunca", "Una vez al año", "Una vez al mes", "Semanalmente", "Todos los días")
  )
}



for (i in names(dplyr::select(db_long, tidyselect::starts_with("p18_")))) {
  db_long[[i]] <- sjlabelled::set_labels(
    x = db_long[[i]],
    labels = c("Nunca", "Casi nunca", "Casi siempre", "Siempre")
  )
}
```
## Meritocracia

### Percepción Esfuerzo

```{r, gráfico alluvial 1, echo=FALSE}
# Paso 1: Preparar datos--------------------------------------------------------
db_long <- db_long %>% filter(!is.na(p1_1) & !is.na(ola))
db_long$p1_1 <- factor(db_long$p1_1, labels= c("Muy en desacuerdo", "En desacuerdo",
                                               "De acuerdo", "Muy de acuerdo"))

# Paso 2: Calcular frecuencias-------------------------------------------------
pe <- db_long %>% 
  group_by(id_estudiante, ola) %>% 
  count(p1_1) %>% 
  group_by(ola) %>% 
  mutate(porcentaje=n/sum(n)) %>% 
  ungroup() %>% 
  na.omit() 

# Paso 3: Agregar etiquetas
etiquetas.pe <- db_long %>%
  group_by(ola, p1_1) %>%
  summarise(count = n(), .groups = "drop") %>%
  group_by(ola) %>%
  mutate(porcentaje = count / sum(count)) %>% 
  na.omit() %>% 
  mutate(id_estudiante = 1)

# Paso 4: Ordenar los factores de la misma forma
pe$p1_1 <- factor(pe$p1_1)
etiquetas.pe$p1_1 <- factor(etiquetas.pe$p1_1)

# Paso 5: Definir colores de las barras
colors <- c("#f1eef6ff","#bdc9e1ff","#74a9cfff","#0570b0ff")

# Paso 6: Graficar
plot_pe <- pe %>% 
  ggplot(aes(x = ola, fill = p1_1, stratum = p1_1,
             alluvium = id_estudiante, y = porcentaje)) +
  ggalluvial::geom_flow(alpha = .66) + 
  ggalluvial::geom_stratum(linetype = 0) +
  scale_y_continuous(labels = scales::percent) + 
  scale_fill_manual(values = colors) +
  geom_shadowtext(data = etiquetas.pe,
                  aes(label = ifelse(porcentaje > 0, scales::percent(porcentaje, accuracy = .1), "")),
                  position = position_stack(vjust = .5),
                  show.legend = FALSE,
                  size = 4,
                  color = 'white',
                  bg.colour = 'grey30') +
  labs(y = "Porcentaje",
       x = c("Olas"),
       fill = "Grado de acuerdo",
       caption = "Fuente: EDUMER",
       title = "Figura 1: En esta escuela quienes se esfuerzan\nobtienen buenas notas") +
  theme(legend.position = "bottom") + 
  theme_blank()

plot_pe
```

```{r, dona-curso, echo=FALSE }
# gráfico: esfuerzo y curso

# dona curso: Básica

basica_esfuerzo <- db_students_w02 %>% dplyr::filter(nivel_estudiante_o2=="Básica") %>% 
  dplyr::select(p2_1_o2) #se filtran valores para esa categoría del curso

basica_esfuerzo = round(prop.table(table(categorias=basica_esfuerzo$p2_1_o2)),2) #se crean variables 'categoria' y 'Freq' del objeto

basica_esfuerzo = as.data.frame(basica_esfuerzo) #convertimos el objeto en data.frame

basica_esfuerzo$categorias <- factor(basica_esfuerzo$categorias, levels = c(1, 2, 3, 4), labels = c("Muy en desacuerdo", "Desacuerdo", "De acuerdo", "Muy de acuerdo")) 

plot_basica_esfuerzo<-ggplot(basica_esfuerzo,aes(x=2,y=-Freq, fill=categorias))+
  geom_bar(stat = "identity", 
           color="white")+
  geom_text(aes(label = scales::percent(Freq)),
            position=position_stack(vjust=0.5),color="black",size=4.5)+
  coord_polar(theta = "y")+
  scale_fill_brewer(palette = "Blues")+
  theme_void()+
  theme(legend.title = element_blank(),
        plot.title = element_text(size=12, face="bold", hjust=0.5))+
  xlim(0.5,2.5) +
  labs(title="Estudiantes de básica") #graficamos


# dona curso: Media

# categoría media
media_esfuerzo <- db_students_w02 %>% filter(nivel_estudiante_o2=="Media") %>% 
  dplyr::select(p2_1_o2) 

media_esfuerzo = round(prop.table(table(categorias=media_esfuerzo$p2_1_o2)),2)  

media_esfuerzo = as.data.frame(media_esfuerzo)

media_esfuerzo$categorias <- factor(media_esfuerzo$categorias, levels = c(1, 2, 3, 4), labels = c("Muy en desacuerdo", "Desacuerdo", "De acuerdo", "Muy de acuerdo")) 

plot_media_esfuerzo<-ggplot(media_esfuerzo,aes(x=2,y=-Freq, fill=categorias))+
  geom_bar(stat = "identity", 
           color="white")+
  geom_text(aes(label = scales::percent(Freq)),
            position=position_stack(vjust=0.5),color="black",size=4.5)+
  coord_polar(theta = "y")+
  scale_fill_brewer(palette = "Blues")+
  theme_void()+
  theme(legend.title = element_blank(),
        plot.title = element_text(size=12, face="bold", hjust=0.5))+
  xlim(0.5,2.5) +
  labs(title="Estudiantes de media") 

esfuerzo_curso <- ggarrange(
  plot_basica_esfuerzo, 
  plot_media_esfuerzo,
  common.legend = TRUE, 
  ncol = 2, 
  legend = "bottom")

# Agregar una etiqueta global centrada
plot_es_percep_curso <- annotate_figure(
  esfuerzo_curso,
  top = text_grob(
    "Figura : En esta escuela, quienes se esfuerzan obtienen buenas notas",
    size = 12, 
    face = "italic", 
    color = "black",
    hjust = 0.5))

plot_es_percep_curso
```

### Percepción Talento

```{r, gráfico 2, echo=FALSE}
# Paso 1: Preparar datos--------------------------------------------------------
db_long <- db_long %>% filter(!is.na(p1_2) & !is.na(ola))
db_long$p1_2 <- factor(db_long$p1_2, labels= c("Muy en desacuerdo", "En desacuerdo",
                                               "De acuerdo", "Muy de acuerdo"))

# Paso 2: Calcular frecuencias-------------------------------------------------
pe <- db_long %>% 
  group_by(id_estudiante, ola) %>% 
  count(p1_2) %>% 
  group_by(ola) %>% 
  mutate(porcentaje=n/sum(n)) %>% 
  ungroup() %>% 
  na.omit() 

# Paso 3: Agregar etiquetas
etiquetas.pe <- db_long %>%
  group_by(ola, p1_2) %>%
  summarise(count = n(), .groups = "drop") %>%
  group_by(ola) %>%
  mutate(porcentaje = count / sum(count)) %>% 
  na.omit() %>% 
  mutate(id_estudiante = 1)

# Paso 4: Ordenar los factores de la misma forma
pe$p1_2 <- factor(pe$p1_2)
etiquetas.pe$p1_2 <- factor(etiquetas.pe$p1_2)

# Paso 5: Definir colores de las barras
colors <- c("#f1eef6ff","#bdc9e1ff","#74a9cfff","#0570b0ff")

# Paso 6: Graficar
plot_pe <- pe %>% 
  ggplot(aes(x = ola, fill = p1_2, stratum = p1_2,
             alluvium = id_estudiante, y = porcentaje)) +
  ggalluvial::geom_flow(alpha = .66) + 
  ggalluvial::geom_stratum(linetype = 0) +
  scale_y_continuous(labels = scales::percent) + 
  scale_fill_manual(values = colors) +
  geom_shadowtext(data = etiquetas.pe,
                  aes(label = ifelse(porcentaje > 0, scales::percent(porcentaje, accuracy = .1), "")),
                  position = position_stack(vjust = .5),
                  show.legend = FALSE,
                  size = 4,
                  color = 'white',
                  bg.colour = 'grey30') +
  labs(y = "Porcentaje",
       x = c("Olas"),
       fill = "Grado de acuerdo",
       caption = "Fuente: EDUMER",
       title = "Figura 2: En Chile, las personas son recompensadas por su \n inteligencia y habilidad") +
  theme(legend.position = "bottom") + 
  theme_blank()

plot_pe
```

### Percepción Padres Ricos

```{r, gráfico 3, echo=FALSE}
# Paso 1: Preparar datos--------------------------------------------------------
db_long <- db_long %>% filter(!is.na(p1_3) & !is.na(ola))
db_long$p1_3 <- factor(db_long$p1_3, labels= c("Muy en desacuerdo", "En desacuerdo",
                                               "De acuerdo", "Muy de acuerdo"))

# Paso 2: Calcular frecuencias-------------------------------------------------
pe <- db_long %>% 
  group_by(id_estudiante, ola) %>% 
  count(p1_3) %>% 
  group_by(ola) %>% 
  mutate(porcentaje=n/sum(n)) %>% 
  ungroup() %>% 
  na.omit() 

# Paso 3: Agregar etiquetas
etiquetas.pe <- db_long %>%
  group_by(ola, p1_3) %>%
  summarise(count = n(), .groups = "drop") %>%
  group_by(ola) %>%
  mutate(porcentaje = count / sum(count)) %>% 
  na.omit() %>% 
  mutate(id_estudiante = 1)

# Paso 4: Ordenar los factores de la misma forma
pe$p1_3 <- factor(pe$p1_3)
etiquetas.pe$p1_3 <- factor(etiquetas.pe$p1_3)

# Paso 5: Definir colores de las barras
colors <- c("#f1eef6ff","#bdc9e1ff","#74a9cfff","#0570b0ff")

# Paso 6: Graficar
plot_pe <- pe %>% 
  ggplot(aes(x = ola, fill = p1_3, stratum = p1_3,
             alluvium = id_estudiante, y = porcentaje)) +
  ggalluvial::geom_flow(alpha = .66) + 
  ggalluvial::geom_stratum(linetype = 0) +
  scale_y_continuous(labels = scales::percent) + 
  scale_fill_manual(values = colors) +
  geom_shadowtext(data = etiquetas.pe,
                  aes(label = ifelse(porcentaje > 0, scales::percent(porcentaje, accuracy = .1), "")),
                  position = position_stack(vjust = .5),
                  show.legend = FALSE,
                  size = 4,
                  color = 'white',
                  bg.colour = 'grey30') +
  labs(y = "Porcentaje",
       x = c("Olas"),
       fill = "Grado de acuerdo",
       caption = "Fuente: EDUMER",
       title = "Figura 3: En Chile, a quienes tienen padres ricos les va mucho \n mejor en la vida.") +
  theme(legend.position = "bottom") + 
  theme_blank()

plot_pe
```

### Percepción Buenos Contactos

```{r, gráfico 4, echo=FALSE}
# Paso 1: Preparar datos--------------------------------------------------------
db_long <- db_long %>% filter(!is.na(p1_4) & !is.na(ola))
db_long$p1_4 <- factor(db_long$p1_4, labels= c("Muy en desacuerdo", "En desacuerdo",
                                               "De acuerdo", "Muy de acuerdo"))

# Paso 2: Calcular frecuencias-------------------------------------------------
pe <- db_long %>% 
  group_by(id_estudiante, ola) %>% 
  count(p1_4) %>% 
  group_by(ola) %>% 
  mutate(porcentaje=n/sum(n)) %>% 
  ungroup() %>% 
  na.omit() 

# Paso 3: Agregar etiquetas
etiquetas.pe <- db_long %>%
  group_by(ola, p1_4) %>%
  summarise(count = n(), .groups = "drop") %>%
  group_by(ola) %>%
  mutate(porcentaje = count / sum(count)) %>% 
  na.omit() %>% 
  mutate(id_estudiante = 1)

# Paso 4: Ordenar los factores de la misma forma
pe$p1_4 <- factor(pe$p1_4)
etiquetas.pe$p1_4 <- factor(etiquetas.pe$p1_4)

# Paso 5: Definir colores de las barras
colors <- c("#f1eef6ff","#bdc9e1ff","#74a9cfff","#0570b0ff")

# Paso 6: Graficar
plot_pe <- pe %>% 
  ggplot(aes(x = ola, fill = p1_4, stratum = p1_4,
             alluvium = id_estudiante, y = porcentaje)) +
  ggalluvial::geom_flow(alpha = .66) + 
  ggalluvial::geom_stratum(linetype = 0) +
  scale_y_continuous(labels = scales::percent) + 
  scale_fill_manual(values = colors) +
  geom_shadowtext(data = etiquetas.pe,
                  aes(label = ifelse(porcentaje > 0, scales::percent(porcentaje, accuracy = .1), "")),
                  position = position_stack(vjust = .5),
                  show.legend = FALSE,
                  size = 4,
                  color = 'white',
                  bg.colour = 'grey30') +
  labs(y = "Porcentaje",
       x = c("Olas"),
       fill = "Grado de acuerdo",
       caption = "Fuente: EDUMER",
       title = "Figura 4:En Chile, quienes tienen buenos contactos les va mejor \n en la vida.") +
  theme(legend.position = "bottom") + 
  theme_blank()

plot_pe
```

### Preferencia Esfuerzo

```{r, gráfico 5, echo=FALSE}
# Paso 1: Preparar datos--------------------------------------------------------
db_long <- db_long %>% filter(!is.na(p1_5) & !is.na(ola))
db_long$p1_5 <- factor(db_long$p1_5, labels= c("Muy en desacuerdo", "En desacuerdo",
                                               "De acuerdo", "Muy de acuerdo"))

# Paso 2: Calcular frecuencias-------------------------------------------------
pe <- db_long %>% 
  group_by(id_estudiante, ola) %>% 
  count(p1_5) %>% 
  group_by(ola) %>% 
  mutate(porcentaje=n/sum(n)) %>% 
  ungroup() %>% 
  na.omit() 

# Paso 3: Agregar etiquetas
etiquetas.pe <- db_long %>%
  group_by(ola, p1_5) %>%
  summarise(count = n(), .groups = "drop") %>%
  group_by(ola) %>%
  mutate(porcentaje = count / sum(count)) %>% 
  na.omit() %>% 
  mutate(id_estudiante = 1)

# Paso 4: Ordenar los factores de la misma forma
pe$p1_1 <- factor(pe$p1_5)
etiquetas.pe$p1_5 <- factor(etiquetas.pe$p1_5)

# Paso 5: Definir colores de las barras
colors <- c("#f1eef6ff","#bdc9e1ff","#74a9cfff","#0570b0ff")

# Paso 6: Graficar
plot_pe <- pe %>% 
  ggplot(aes(x = ola, fill = p1_5, stratum = p1_5,
             alluvium = id_estudiante, y = porcentaje)) +
  ggalluvial::geom_flow(alpha = .66) + 
  ggalluvial::geom_stratum(linetype = 0) +
  scale_y_continuous(labels = scales::percent) + 
  scale_fill_manual(values = colors) +
  geom_shadowtext(data = etiquetas.pe,
                  aes(label = ifelse(porcentaje > 0, scales::percent(porcentaje, accuracy = .1), "")),
                  position = position_stack(vjust = .5),
                  show.legend = FALSE,
                  size = 4,
                  color = 'white',
                  bg.colour = 'grey30') +
  labs(y = "Porcentaje",
       x = c("Olas"),
       fill = "Grado de acuerdo",
       caption = "Fuente: EDUMER",
       title = "Figura 5: Quienes más se esfuerzan deberían obtener mayores \n recompensas que quienes se esfuerzan menos.") +
  theme(legend.position = "bottom") + 
  theme_blank()

plot_pe
```

### Preferencia Talento

```{r, gráfico 6, echo=FALSE}
# Paso 1: Preparar datos--------------------------------------------------------
db_long <- db_long %>% filter(!is.na(p1_6) & !is.na(ola))
db_long$p1_6 <- factor(db_long$p1_6, labels= c("Muy en desacuerdo", "En desacuerdo",
                                               "De acuerdo", "Muy de acuerdo"))

# Paso 2: Calcular frecuencias-------------------------------------------------
pe <- db_long %>% 
  group_by(id_estudiante, ola) %>% 
  count(p1_6) %>% 
  group_by(ola) %>% 
  mutate(porcentaje=n/sum(n)) %>% 
  ungroup() %>% 
  na.omit() 

# Paso 3: Agregar etiquetas
etiquetas.pe <- db_long %>%
  group_by(ola, p1_6) %>%
  summarise(count = n(), .groups = "drop") %>%
  group_by(ola) %>%
  mutate(porcentaje = count / sum(count)) %>% 
  na.omit() %>% 
  mutate(id_estudiante = 1)

# Paso 4: Ordenar los factores de la misma forma
pe$p1_6 <- factor(pe$p1_6)
etiquetas.pe$p1_6 <- factor(etiquetas.pe$p1_6)

# Paso 5: Definir colores de las barras
colors <- c("#f1eef6ff","#bdc9e1ff","#74a9cfff","#0570b0ff")
# Paso 6: Graficar
plot_pe <- pe %>% 
  ggplot(aes(x = ola, fill = p1_6, stratum = p1_6,
             alluvium = id_estudiante, y = porcentaje)) +
  ggalluvial::geom_flow(alpha = .66) + 
  ggalluvial::geom_stratum(linetype = 0) +
  scale_y_continuous(labels = scales::percent) + 
  scale_fill_manual(values = colors) +
  geom_shadowtext(data = etiquetas.pe,
                  aes(label = ifelse(porcentaje > 0, scales::percent(porcentaje, accuracy = .1), "")),
                  position = position_stack(vjust = .5),
                  show.legend = FALSE,
                  size = 4,
                  color = 'white',
                  bg.colour = 'grey30') +
  labs(y = "Porcentaje",
       x = c("Olas"),
       fill = "Grado de acuerdo",
       caption = "Fuente: EDUMER",
       title = "Figura 6: Quienes poseen más talento deberían obtener mayores \n recompensas que quienes poseen menos talento.") +
  theme(legend.position = "bottom") + 
  theme_blank()

plot_pe
```

### Preferencia Padres ricos

```{r, gráfico 7, echo=FALSE}
# Paso 1: Preparar datos--------------------------------------------------------
db_long <- db_long %>% filter(!is.na(p1_7) & !is.na(ola))
db_long$p1_7 <- factor(db_long$p1_7, labels= c("Muy en desacuerdo", "En desacuerdo",
                                               "De acuerdo", "Muy de acuerdo"))

# Paso 2: Calcular frecuencias-------------------------------------------------
pe <- db_long %>% 
  group_by(id_estudiante, ola) %>% 
  count(p1_7) %>% 
  group_by(ola) %>% 
  mutate(porcentaje=n/sum(n)) %>% 
  ungroup() %>% 
  na.omit() 

# Paso 3: Agregar etiquetas
etiquetas.pe <- db_long %>%
  group_by(ola, p1_7) %>%
  summarise(count = n(), .groups = "drop") %>%
  group_by(ola) %>%
  mutate(porcentaje = count / sum(count)) %>% 
  na.omit() %>% 
  mutate(id_estudiante = 1)

# Paso 4: Ordenar los factores de la misma forma
pe$p1_7 <- factor(pe$p1_7)
etiquetas.pe$p1_7 <- factor(etiquetas.pe$p1_7)

# Paso 5: Definir colores de las barras
colors <- c("#f1eef6ff","#bdc9e1ff","#74a9cfff","#0570b0ff")

# Paso 6: Graficar
plot_pe <- pe %>% 
  ggplot(aes(x = ola, fill = p1_7, stratum = p1_7,
             alluvium = id_estudiante, y = porcentaje)) +
  ggalluvial::geom_flow(alpha = .66) + 
  ggalluvial::geom_stratum(linetype = 0) +
  scale_y_continuous(labels = scales::percent) + 
  scale_fill_manual(values = colors) +
  geom_shadowtext(data = etiquetas.pe,
                  aes(label = ifelse(porcentaje > 0, scales::percent(porcentaje, accuracy = .1), "")),
                  position = position_stack(vjust = .5),
                  show.legend = FALSE,
                  size = 4,
                  color = 'white',
                  bg.colour = 'grey30') +
  labs(y = "Porcentaje",
       x = c("Olas"),
       fill = "Grado de acuerdo",
       caption = "Fuente: EDUMER",
       title = "Figura 7:  Está bien que quienes tienen padres ricos les vaya \n bien en la vida.") +
  theme(legend.position = "bottom") + 
  theme_blank()

plot_pe
```

### Preferencia Buenos contactos

```{r, gráfico 8, echo=FALSE}
# Paso 1: Preparar datos--------------------------------------------------------
db_long <- db_long %>% filter(!is.na(p1_8) & !is.na(ola))
db_long$p1_8 <- factor(db_long$p1_8, labels= c("Muy en desacuerdo", "En desacuerdo",
                                               "De acuerdo", "Muy de acuerdo"))

# Paso 2: Calcular frecuencias-------------------------------------------------
pe <- db_long %>% 
  group_by(id_estudiante, ola) %>% 
  count(p1_8) %>% 
  group_by(ola) %>% 
  mutate(porcentaje=n/sum(n)) %>% 
  ungroup() %>% 
  na.omit() 

# Paso 3: Agregar etiquetas
etiquetas.pe <- db_long %>%
  group_by(ola, p1_8) %>%
  summarise(count = n(), .groups = "drop") %>%
  group_by(ola) %>%
  mutate(porcentaje = count / sum(count)) %>% 
  na.omit() %>% 
  mutate(id_estudiante = 1)

# Paso 4: Ordenar los factores de la misma forma
pe$p1_8 <- factor(pe$p1_8)
etiquetas.pe$p1_8 <- factor(etiquetas.pe$p1_8)

# Paso 5: Definir colores de las barras
colors <- c("#f1eef6ff","#bdc9e1ff","#74a9cfff","#0570b0ff")

# Paso 6: Graficar
plot_pe <- pe %>% 
  ggplot(aes(x = ola, fill = p1_8, stratum = p1_8,
             alluvium = id_estudiante, y = porcentaje)) +
  ggalluvial::geom_flow(alpha = .66) + 
  ggalluvial::geom_stratum(linetype = 0) +
  scale_y_continuous(labels = scales::percent) + 
  scale_fill_manual(values = colors) +
  geom_shadowtext(data = etiquetas.pe,
                  aes(label = ifelse(porcentaje > 0, scales::percent(porcentaje, accuracy = .1), "")),
                  position = position_stack(vjust = .5),
                  show.legend = FALSE,
                  size = 4,
                  color = 'white',
                  bg.colour = 'grey30') +
  labs(y = "Porcentaje",
       x = c("Olas"),
       fill = "Grado de acuerdo",
       caption = "Fuente: EDUMER",
       title = "Figura 8: Está bien que quienes tienen buenos contactos les \n vaya bien en la vida.") +
  theme(legend.position = "bottom") + 
  theme_blank()

plot_pe
```

### Percepción Oportunidades

```{r, gráfico 9, echo=FALSE}
# Paso 1: Preparar datos--------------------------------------------------------
db_long <- db_long %>% filter(!is.na(p1_9) & !is.na(ola))
db_long$p1_9 <- factor(db_long$p1_9, labels= c("Muy en desacuerdo", "En desacuerdo",
                                               "De acuerdo", "Muy de acuerdo"))

# Paso 2: Calcular frecuencias-------------------------------------------------
pe <- db_long %>% 
  group_by(id_estudiante, ola) %>% 
  count(p1_9) %>% 
  group_by(ola) %>% 
  mutate(porcentaje=n/sum(n)) %>% 
  ungroup() %>% 
  na.omit() 

# Paso 3: Agregar etiquetas
etiquetas.pe <- db_long %>%
  group_by(ola, p1_9) %>%
  summarise(count = n(), .groups = "drop") %>%
  group_by(ola) %>%
  mutate(porcentaje = count / sum(count)) %>% 
  na.omit() %>% 
  mutate(id_estudiante = 1)

# Paso 4: Ordenar los factores de la misma forma
pe$p1_9 <- factor(pe$p1_9)
etiquetas.pe$p1_9 <- factor(etiquetas.pe$p1_9)

# Paso 5: Definir colores de las barras
colors <- c("#f1eef6ff","#bdc9e1ff","#74a9cfff","#0570b0ff")

# Paso 6: Graficar
plot_pe <- pe %>% 
  ggplot(aes(x = ola, fill = p1_9, stratum = p1_9,
             alluvium = id_estudiante, y = porcentaje)) +
  ggalluvial::geom_flow(alpha = .66) + 
  ggalluvial::geom_stratum(linetype = 0) +
  scale_y_continuous(labels = scales::percent) + 
  scale_fill_manual(values = colors) +
  geom_shadowtext(data = etiquetas.pe,
                  aes(label = ifelse(porcentaje > 0, scales::percent(porcentaje, accuracy = .1), "")),
                  position = position_stack(vjust = .5),
                  show.legend = FALSE,
                  size = 4,
                  color = 'white',
                  bg.colour = 'grey30') +
  labs(y = "Porcentaje",
       x = c("Olas"),
       fill = "Grado de acuerdo",
       caption = "Fuente: EDUMER",
       title = "Figura 9:  En Chile, todas las personas tienen las mismas \n oportunidades para salir adelante..") +
  theme(legend.position = "bottom") + 
  theme_blank()

plot_pe
```

### Percepción Meritocracia

```{r, gráfico 10, echo=FALSE}
# Paso 1: Preparar datos--------------------------------------------------------
db_long <- db_long %>% filter(!is.na(p1_10) & !is.na(ola))
db_long$p1_10 <- factor(db_long$p1_10, labels= c("Muy en desacuerdo", "En desacuerdo",
                                               "De acuerdo", "Muy de acuerdo"))

# Paso 2: Calcular frecuencias-------------------------------------------------
pe <- db_long %>% 
  group_by(id_estudiante, ola) %>% 
  count(p1_10) %>% 
  group_by(ola) %>% 
  mutate(porcentaje=n/sum(n)) %>% 
  ungroup() %>% 
  na.omit() 

# Paso 3: Agregar etiquetas
etiquetas.pe <- db_long %>%
  group_by(ola, p1_10) %>%
  summarise(count = n(), .groups = "drop") %>%
  group_by(ola) %>%
  mutate(porcentaje = count / sum(count)) %>% 
  na.omit() %>% 
  mutate(id_estudiante = 1)

# Paso 4: Ordenar los factores de la misma forma
pe$p1_10 <- factor(pe$p1_10)
etiquetas.pe$p1_10 <- factor(etiquetas.pe$p1_10)

# Paso 5: Definir colores de las barras
colors <- c("#f1eef6ff","#bdc9e1ff","#74a9cfff","#0570b0ff")

# Paso 6: Graficar
plot_pe <- pe %>% 
  ggplot(aes(x = ola, fill = p1_10, stratum = p1_10,
             alluvium = id_estudiante, y = porcentaje)) +
  ggalluvial::geom_flow(alpha = .66) + 
  ggalluvial::geom_stratum(linetype = 0) +
  scale_y_continuous(labels = scales::percent) + 
  scale_fill_manual(values = colors) +
  geom_shadowtext(data = etiquetas.pe,
                  aes(label = ifelse(porcentaje > 0, scales::percent(porcentaje, accuracy = .1), "")),
                  position = position_stack(vjust = .5),
                  show.legend = FALSE,
                  size = 4,
                  color = 'white',
                  bg.colour = 'grey30') +
  labs(y = "Porcentaje",
       x = c("Olas"),
       fill = "Grado de acuerdo",
       caption = "Fuente: EDUMER",
       title = "Figura 10: En Chile, todas las personas obtienen lo que merecen.") +
  theme(legend.position = "bottom") + 
  theme_blank()

plot_pe
```
