# Reporte metodológico

Para abordar la pregunta de investigación se lleva a cabo el Estudio Panel "**Educación y Meritocracia - EDUMER**" entre el año 2023 y 2024, encuestando a solo a estudiantes de enseñanza básica y media en esta segunda ola del estudio.

Este informe refiere a la *segunda ola* del estudio, llevada a cabo en el año 2024. La base de datos cuenta con un total de 674 casos correspondiente a estudiantes.

El cuestionario EDUMER presenta variables sobre meritocracia, desigualdad, ciudadanía, sociodemográficas, y variables referidas a un *experimento distribucional de encuesta* (DSE). Para efectos de este informe, se presentarán preguntas sobre *creencias en la meritocracia* y *justicia en las notas*, las cuales se dispondrán en el primer gran módulo de Meritocracia (distinguida en su presencia en la sociedad chilena y en el aula); preguntas *actitudinales* y de *participación política*, enmarcadas en el segundo gran módulo de Ciudadanía; preguntas sociodemográficas del estudiante, que permiten caracterizar el *contexto socioeconómico de la escuela* (nivel educacional máximo alcanzado por el padre y la madre) y el *capital cultural* del mismo (medido por la cantidad de libros presentes en el hogar), así también como su *género* y *curso; y las preguntas referidas al experimento de distribución de décimas*.

A continuación, se presentarán análisis descriptivos univariados de las preguntas referidas a las ideas de Meritocriacia, Ciudadanía y Justicia educacional. Cada sección muestra primero las diferencias entre estudiantes de básica y media. Finalmente, se muestran diferencias según las características sociodemográficas del estudiante (nivel educacional de los apoderados, género y cantidad de libros en el hogar).
